# Generated by Django 3.1 on 2020-09-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0012_auto_20200806_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='oferta',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
