# Generated by Django 3.1 on 2020-09-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0013_libro_oferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='estado',
        ),
    ]
