# Generated by Django 3.1 on 2020-09-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0014_remove_libro_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='oferta',
        ),
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
