# Generated by Django 3.1 on 2020-09-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0015_auto_20200902_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='tags',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
